# Generated by Django 5.2 on 2025-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_names', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('user_active', models.BooleanField(default=True)),
                ('user_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
