# Generated by Django 5.2 on 2025-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_admin',
            new_name='user_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='user_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
