# Generated by Django 5.2 on 2025-04-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_user_admin_user_user_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_superuser',
            new_name='is_superuser',
        ),
    ]
