# Generated by Django 5.2 on 2025-04-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_user_bio_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Biografía'),
        ),
    ]
