# Generated by Django 5.2 on 2025-04-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
