# Generated by Django 5.2 on 2025-04-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Name',
            new_name='name',
        ),
    ]
