# Generated by Django 5.2 on 2025-04-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_rename_name_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.subject', verbose_name='Asignatura'),
        ),
    ]
