# Generated by Django 5.2 on 2025-05-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_alter_subject_options_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.subject', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Nombre de la asignatura'),
        ),
    ]
